// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReserveFlow.Modules.Reporting.Infrastructure.Database;

#nullable disable

namespace ReserveFlow.Modules.Reporting.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReserveFlow.Modules.Reporting.Domain.Reports.DailyBookingReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CancelledBookings")
                        .HasColumnType("integer")
                        .HasColumnName("cancelled_bookings");

                    b.Property<int>("CompletedBookings")
                        .HasColumnType("integer")
                        .HasColumnName("completed_bookings");

                    b.Property<int>("CreatedBookings")
                        .HasColumnType("integer")
                        .HasColumnName("created_bookings");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("NoShowBookings")
                        .HasColumnType("integer")
                        .HasColumnName("no_show_bookings");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ux_daily_booking_reports_tenant_date");

                    b.ToTable("daily_booking_reports", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
