<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\ReserveFlow.Common.Application\ReserveFlow.Common.Application.csproj" />
    <ProjectReference Include="..\ReserveFlow.Modules.Notifications.Domain\ReserveFlow.Modules.Notifications.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
