<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\ReserveFlow.Common.Infrastructure\ReserveFlow.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\ReserveFlow.Modules.Bookings.Application\ReserveFlow.Modules.Bookings.Application.csproj" />
    <ProjectReference Include="..\ReserveFlow.Modules.Bookings.Domain\ReserveFlow.Modules.Bookings.Domain.csproj" />
    <ProjectReference Include="..\ReserveFlow.Modules.Bookings.Presentation\ReserveFlow.Modules.Bookings.Presentation.csproj" />
    <ProjectReference Include="..\..\Notifications\ReserveFlow.Modules.Notifications.Application\ReserveFlow.Modules.Notifications.Application.csproj" />
    <ProjectReference Include="..\..\Notifications\ReserveFlow.Modules.Notifications.Domain\ReserveFlow.Modules.Notifications.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
